### ISSUE TITLE
Transport Mod (transportmod) has failed to load correctly

### ISSUE THREAD

**Issue by DotEXEGaming** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#11]
I am getting an error which is as follows: "**java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeSpawnEggItem**"
[crash-2022-07-19_16.10.50-fml.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9142443/crash-2022-07-19_16.10.50-fml.txt)
 The crash log is also attached.

**Comment by Rinventor** [comment]
Which mod version? And which Minecraft version?

**Comment by DotEXEGaming** [comment]
minecraft 1.16.5 with the appropriate gecko library. i have tried with both mod versions each yielding the same error. the one in the report is 7.7

**Comment by DotEXEGaming** [comment]
[crash-2022-07-19_16.59.53-fml.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9142842/crash-2022-07-19_16.59.53-fml.txt)
log for 9.3

**Comment by Rinventor** [comment]
What forge version are you using?

**Comment by DotEXEGaming** [comment]
36.2.4

**Comment by Rinventor** [comment]
Updating Forge to recommended 36.2.34 might fix this problem.

**Comment by DotEXEGaming** [comment]
downgraded to 36.2.3 (only one close to .34 GDLauncher supports) and no dice, same error.

**Comment by Rinventor** [comment]
Yeah, I get the same error with 36.2.4 and 36.2.20. Error goes away from 36.2.31 and above, I think. I don't think it would be possible to fix it some other way.

**Comment by DotEXEGaming** [comment]
Mod working now after update! Thank you
