### ISSUE TITLE
Unable to join multiplayer server with mod installed

### ISSUE THREAD

**Issue by MrPotatoezzz** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#13]
Its not possible to join a multiplayer server with this mod installed, client side just says disconnected. Server console says invalid playerdata.

Public+Transport+Mod+9.3-1.18.2
geckolib-forge-1.18-3.0.28

both installed on the server and client

**Comment by Rinventor** [comment]
Going to be fixed in the next version. Release date probably 10th of August.

**Comment by MagicalAlexey** [comment]
By the way, this is very disturbing, I wanted to launch a server with this mod, and then a lapel and a turn
