### ISSUE TITLE
Platform edge glass

### ISSUE THREAD

**Issue by rsdworker** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#14]
the bug with new platform edge doors 
I would split in two sections one relates with underground station
other is relates with above ground stations
so seems there is bug with glass placement - I can see lines on one side

photo
![image](https://user-images.githubusercontent.com/6688223/184718271-991eb0e5-9bec-46a5-ac5b-25a931e2ecda.png)

you can see yellow strips on one side 

other bug 

![image](https://user-images.githubusercontent.com/6688223/184719158-7b6333f6-e41d-48cd-b79c-37c808af704e.png)

this shows the glass isn't correctly auto aligning

placement causes crash

seen in logs

[crash-2022-08-15_22.12.23-server.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9340082/crash-2022-08-15_22.12.23-server.txt)

Overground Platform edge glass issues - this one seems very rare - I had no crashes apart with one crash

sometimes wrong facing can happen 

like this

![image](https://user-images.githubusercontent.com/6688223/184723911-18012074-7453-4b01-a148-40f5630f8528.png)

other crash happens if you place something close other glass wall such end wall

[crash-2022-08-15_22.58.23-server.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9340067/crash-2022-08-15_22.58.23-server.txt)

version 1.18.2 forge

**Comment by Rinventor** [comment]
- Wrong facing happens when the first glass block is placed the wrong way. Then it will override all the other blocks facings as well and that leads to situation where the whole screen is just wrong.
- The screen is right now designed to be just one row. In your case you have built a corner as well (which I didn't think of) which is confusing the automatic placement system and thus crashing the game.

**Comment by rsdworker** [comment]
Great thats i hope its fixed in next version

**Comment by rsdworker** [comment]
Crash when trying fix the hole
[crash-2022-08-16_11.20.06-server.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9349828/crash-2022-08-16_11.20.06-server.txt)
