### ISSUE TITLE
underground to overground bug

### ISSUE THREAD

**Issue by rsdworker** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#16]
here a transction going up to ground but its don't automatically change to overground aka removing tunnels 

![image](https://user-images.githubusercontent.com/6688223/184734978-988e9004-bbd4-4859-88b2-9e9c834ed63b.png)

while overground to Underground works fine without tunnel walls till its deep enough to create tunnels

**Comment by Rinventor** [comment]
When you are coming from the underground and have arrived to overground and want no tunnels any more, then make sure that the builder sees the sky. If there are no blocks above the builder's head then it will place the overground structures.
