### ISSUE TITLE
Scooter crashes server

### ISSUE THREAD

**Issue by MrPotatoezzz** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#17]
When sitting on a scooter on a multiplayer server the server crashes, everytime this player on the scooter joins he is still on the scooter and immidiatly crashes the server again. 

forge 40.1.0
minecraft 1.18.2
modversion 10.0.1

**Comment by Rinventor** [comment]
Can you send a debug.log

**Comment by MrPotatoezzz** [comment]
Sorry but I dont know what you mean with a debug.log, do you mean crash report?

**Comment by Rinventor** [comment]
A crash report, yes. But in the logs folder there should be a debug.txt file which would contain the full error log.
