### ISSUE TITLE
Shifting gears on multyplayer crashes server

### ISSUE THREAD

**Issue by MrPotatoezzz** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#18]
When shifting gears in a ridable vehicle the multyplayer server crashes.

forge 40.1.0
minecraft 1.18.2
modversion 10.0.1

**Comment by Rinventor** [comment]
Crash debug.log?

**Comment by Rinventor** [comment]
All key events cause crashes, not only shifting gears.

**Comment by MrPotatoezzz** [comment]
Sorry, I was a bit bussy the last few days, do you still need the debug.log?

**Comment by Rinventor** [comment]
No, I'm already dealing with much bigger issue causing this problem.

**Comment by Rinventor** [comment]
Fixed in 10.1
