### ISSUE TITLE
keyboard setup (controls)

### ISSUE THREAD

**Issue by darkShadowexe** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#19]
i saw your video on the mod and it seems like there are new options in the menu which were not in the video

can you pls help

settings shown in the video 
![chrome_lPNRMexSIM](https://user-images.githubusercontent.com/78064217/186178328-9c6dbd20-d95a-45f3-90dc-9724fd622ca1.png)

settings on my minecraft screen
![javaw_iC0Sm4Nvfj](https://user-images.githubusercontent.com/78064217/186178558-0e102ed8-4b74-4064-a70d-f85f308efb13.png)

i also looked through the wiki but no info

**Comment by Rinventor** [comment]
Join our Discord server for any help or questions: https://discord.gg/3BcTppNJ7j
Which kind of keys are you interested in?
