### ISSUE TITLE
placing stations not working

### ISSUE THREAD

**Issue by PTMrtree** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#20]
when i do a busline then i press CTRL + numpad 3 it doesn't place a station I'm  Version 10 of the mod and 1.16.5 for minecraft.

**Comment by Rinventor** [comment]
Are you on multiplayer or singleplayer? If CTRL doesn't work, then try shift.

**Comment by PTMrtree** [comment]
Im singleplayer

**Comment by Rinventor** [comment]
Then control or shift, both should work

**Comment by PTMrtree** [comment]
ok

**Comment by PTMrtree** [comment]
werid neither shift or CTRL work

**Comment by PTMrtree** [comment]
I hope this will be fixed in the next update

**Comment by Rinventor** [comment]
Use older version or wait...
