### ISSUE TITLE
Crash with using Keyboard Number Pad Keys

### ISSUE THREAD

**Issue by Chassx2** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#21]
[crash-2022-09-06_15.26.08-server.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9500181/crash-2022-09-06_15.26.08-server.txt)

Crashes while using the key pad keys on the right of the keyboard. 
You could disassociate the other keys and still press one numpad key and it crashes. 

Log  taken from the server.

**Comment by Rinventor** [comment]
Seems to a massive issue only on 1.16.5 version. Going to be fixed by the end of the month probably...

**Comment by Chassx2** [comment]
Ah, Understood. There a way to circumvent the issue in the meantime? Even if it's to disable the keys?

**Comment by Rinventor** [comment]
Downgrading to version 10.0 should work.
