### ISSUE TITLE
TransportMod (transportmod) has failed to load correctly

### ISSUE THREAD

**Issue by DotEXEGaming** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#22]
I've added the 10.2 version of 1.16.5 version of the mod and the newest geckolib and its throwing this error:
[crash-2022-09-18_14.33.06-fml.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9594080/crash-2022-09-18_14.33.06-fml.txt)

**Comment by Rinventor** [comment]
Here are some solutions you can try:
1. Downgrade geckolib to version 3.0.57
2. Update forge to version 36.2.33 or higher
