### ISSUE TITLE
Railway buider causes to crash the Minecraft.

### ISSUE THREAD

**Issue by michelepestulnik** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#23]
When I spawn the railway builder, it crashes the game.
Specs:
MC 1.18.2
Forge
16gb ram
Version of Public transport mod: 10.2

**Comment by Rinventor** [comment]
Could you add the crash log file. Debug.txt?

**Comment by michelepestulnik** [comment]
[crash-2022-10-07_18.04.23-client.txt](https://github.com/Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition/files/9893422/crash-2022-10-07_18.04.23-client.txt)
Here it is

**Comment by Rinventor** [comment]
Fixed with next update.
