### ISSUE TITLE
New function: RealWeather system

### ISSUE THREAD

**Issue by michelepestulnik** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#24]
This was my idea. It would need Internet to check the weather, in case there is no Internet, the weather will be clear.
New gamerule: RealWeather (true/false)
I think the Do weather cycle should be false.

Settings for Real Weather system are:
Latitude
Longitude
Refresh rate (in minutes)

**Comment by Rinventor** [comment]
Good idea. I'm not sure if I can implement this system into the next version though.

**Comment by Rinventor** [comment]
Not going to be implemented, because to get the required data for example every hour for free forever is too difficult or too expensive.
