### ISSUE TITLE
Traffic junctionbox turns on the blinking yellow light.

### ISSUE THREAD

**Issue by michelle1574** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#27]
When I join the map in night, it shows something like this:
![obraz](https://user-images.githubusercontent.com/70703680/198856954-223d81a4-522d-4354-bf94-2ab2a16d3698.png)
Can you explain me why it is blinking yellow at night? I know that in my town when there are night hours, they also switch the traffic lights to blinking yellow. But why I have something like that in Transport Mod?
Also, if this is a bug, then please fix it.
If it is a normal thing that you expected, can you make a game-rule called: BlinkingYellowTrafficLightAtNight (true/false)
If true, at night would appear the same at night.
If false, the traffic lights would be controlled like on day.

**Comment by Rinventor** [comment]
The blinking yellow at night was intended. Works the same as in real life. Game rule will be added.

**Comment by Rinventor** [comment]
Option to disable added to trafficbox.
