### ISSUE TITLE
Roundabout builder

### ISSUE THREAD

**Issue by michelepestulnik** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#29]
Is there a possibility to put a roundabout in the middle of the junction? Or to implement the roundabout builder?

**Comment by Rinventor** [comment]
At the moment the best option is to build the roundabout manually. Since the transport size will change smaller after the next update the street builder structures will also change. So, should the the roundabout have 4  connections then?

**Comment by Rinventor** [comment]
Feature integrated to street builder.
