### ISSUE TITLE
The test map is not compatible with 1.17.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#3]
The test map has a lot of missing blocks in the roads wall etc. I am guessing that this is where the older version blocks were . I have no idea what was in the holes of missing blocks . can you update the test map

**Comment by Rinventor** [comment]
World updated: https://drive.google.com/file/d/1SaRj7JgtkIwCpMWP3iR3HAa4WFN4MmOj/view?usp=sharing
