### ISSUE TITLE
Entities problem in 1.16.5 (transportmod-7.7-16.5)

### ISSUE THREAD

**Issue by Nonoahah506GX** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#4]
there is a problem in this version of the mod that makes all the entities disappear when I load the chunks, please fix it quickly 👍

**Comment by Rinventor** [comment]
This is a part of a new crash-defuse system that eliminates possibly glitched or stopped or stuck vehicles. When a player joins the world, this part of the system removes all traffic, pedestrians, and transport (It doesn't remove stationary transport vehicles and ridable cars). This helps to load the world quicker and get rid of all glitched vehicles. If you're playing singleplayer you can do the same thing by pressing F3+N twice. 

Now if you don't want the entities to be removed when joining the world you can use a gamerule soon. Version 8.0 should come out in a minimum of 8 hours. This issue will be fixed then.

PS Thanks for the feedback :)

**Comment by Nonoahah506GX** [comment]
thank you, because I love this mod and it's the only one of its kind, I really thank you, see you again :D .
