### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by SuppMind** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#6]
Hello, I ran into a problem that when I create a builder (any), the chat starts to bug, jerking the text until it is impossible to read

**Comment by Rinventor** [comment]
Just out of interest: version 8.0? 1.16.5 or 1.17.1?
I soon will be working on that issue. Going to be fixed in 9.0 update :)

**Comment by SuppMind** [comment]
Mod version: 8.0
Minecraft version: 1.16.5

**Comment by Rinventor** [comment]
There is a temporary fix that might work: Change the chat height or text size under settings.
But as I said before I'm working on solution to that issue.
