### ISSUE TITLE
unresolved entity bug

### ISSUE THREAD

**Issue by Nonoahah506GX** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#8]
well, if you mind spending a little more time on this mod, close the problem, otherwise, I don't want to offend you, but the problem is, say, 50% solved, when I drop an item, it disappears, or when I spawn a chicken or a villager, all that is not hostile, disappears, either it's a command that I didn't enter the game well, or it's the same bug no - solved, I'm waiting for you
![Uploading Films et TV 22_06_2022 21_09_45.png…]()
r answer

**Comment by Rinventor** [comment]
Thanks for your feedback. In your case use these commands:
/gamerule clearVehiclesOnWorldLoad false
/gamerule removeThrownItems false
/gamerule removeExtraEntities false

Let me know if that solve the issue :)

**Comment by Nonoahah506GX** [comment]
Ok, je vais essayer

**Comment by Nonoahah506GX** [comment]
ok I will try

**Comment by Nonoahah506GX** [comment]
perfect, that solves the whole problem, I'll try to make a program that automatically executes the three commands, thank you very much for your work, see you soon 🎉😁
